### ISSUE TITLE
Patch notes

### ISSUE THREAD

**Issue by kriskate** [dotabuff/d2vpkr#13]
[Patch notes japanese](https://github.com/dotabuff/d2vpkr/blob/master/dota/resource/localization/patchnotes/patchnotes_japanese.txt) is empty

Other languages' patch notes do not include all the changes for new patches.

**Comment by jcoene** [comment]
This might be caused by one of these issues:

1) The game doesn't reliably maintain them, in which case there's not much we can do about it
2) The d2vpkr extraction scripts are silently failing on these files

We don't have the bandwidth to investigate, but would accept a patch for the second case if that's the issue.

**Comment by kriskate** [comment]
Thanks for the response.

I've opened the vpk files on Windows via GCFScape and it's an issue regarding the game maintenance.

Closing this issue due to not being related to d2vpkr scripts.
