### ISSUE TITLE
npc_abilities.txt out of date

### ISSUE THREAD

**Issue by devilesk** [dotabuff/d2vpkr#6]
dota/scripts/npc/npc_abilities.txt and the corresponding json version don't reflect the 7.01 patch changes.

The previous commit "update from local instance" looks like it has the correct 7.01 data though. The latest commit says Client 1848 but checking the history of [SteamDB/GameTracking-Dota2](https://github.com/SteamDatabase/GameTracking-Dota2/commits/master/game/dota/scripts/npc/npc_abilities.txt) shows the 7.01 changes on the earlier Client 1845.

**Comment by watbe** [comment]
we're currently having issues with our steambox not fully extracting files all from the VPK. If you need this in json format urgently I suggest pointing your script/application at https://github.com/dotabuff/d2vpkr/tree/037f73209f02394ac3aa2d8ce2f5ddd3c8914b1c for now instead of master while we try and fix this.

**Comment by jcoene** [comment]
Are you still seeing this issue? It appears to have updated `npc_abilities.txt`

**Comment by devilesk** [comment]
Not seeing the issue anymore. Thanks.
